timeManager:
  second: "Секунда"
  seconds: "Секунд"
  minute: "Минута"
  minutes: "Минут"
  hour: "Час"
  hours: "Часов"
  day: "День"
  days: "Дней"

  config:
    onlySeconds: "%seconds% %seconds_placeholder%"
    onlyMinutes: "%minutes% %minutes_placeholder%"
    onlyHours: "%hours% %hours_placeholder%"
    onlyDays: "%days% %days_placeholder%"
    secondsMinutes: "%seconds% %seconds_placeholder% и %minutes% %minutes_placeholder%"
    secondsHours: "%seconds% %seconds_placeholder% и %hours% %hours_placeholder%"
    secondsDays: "%seconds% %seconds_placeholder% и %days% %days_placeholder%"
    secondsMinutesHours: "%seconds% %seconds_placeholder%, %minutes% %minutes_placeholder% и %hours% %hours_placeholder%"
    secondsHoursDays: "%seconds% %seconds_placeholder%, %hours% %hours_placeholder% и %days% %days_placeholder%"
    secondsMinutesDays: "%seconds% %seconds_placeholder%, %minutes% %minutes_placeholder% и %days% %days_placeholder%"
    secondsMinutesHoursDays: "%seconds% %seconds_placeholder%, %minutes% %minutes_placeholder%, %hours% %hours_placeholder% и %days% %days_placeholder%"
    minutesHours: "%minutes% %minutes_placeholder% и %hours% %hours_placeholder%"
    minutesDays: "%minutes% %minutes_placeholder% и %days% %days_placeholder%"
    minutesHoursDays: "%minutes% %minutes_placeholder%, %hours% %hours_placeholder% и %days% %days_placeholder%"
    hoursDays: "%hours% %hours_placeholder% и %days% %days_placeholder%"